project:
  type: website
  output-dir: .
  resources: 
  - shinylive-sw.js
render:
  - "*.qmd"
  - "files/*.qmd"
  - "!CLAUDE.md"

format:
    html:
      theme: lux
      css: www/styles.css


website:
  title: "Analyse de données<br>d'opinion publique"
  navbar:
    logo: "images/logos/Opubliq_V2_couleur-transparent.png"
    search: true
    pinned: true
    tools:
      - icon: twitter
        href: https://twitter.com/HubCadieux25
      - icon: linkedin
        href: https://www.linkedin.com/in/hubert-cadieux-7172571a0
      - icon: github
        href: https://github.com/hubcad25
      - text: '{{< iconify academicons:google-scholar >}}'
        href: https://scholar.google.com/citations?user=VF6HfPoAAAAJ&hl=fr&oi=ao
    collapse-level: 1
    left:
      - text: "Accueil"
        href: index.qmd
      - text: "Nos services"
        href: files/nos_services.html
      - text: "Contact"
        href: files/contact.html
      - text: "À propos"
        href: files/a_propos.html
  page-footer:
    left: "© 2025 Opubliq." 
    right: 
      - text: "Accueil"
        href: index.qmd
      - text: "VISION Opubliq"
        href: files/vision_opubliq.html
      - text: "Nos services"
        href: files/nos_services.html
      - text: "Contact"
        href: files/contact.html
      - text: "À propos"
        href: files/a_propos.html 